name: Deploy VRMS Frontend

on:
  push:
    branches:
      - vrms/qa


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \          
            -t vrms:frontend .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker tag vrms:frontend $DOCKER_HUB_USERNAME/vrms:frontend
          docker push $DOCKER_HUB_USERNAME/vrms:frontend

      - name: Connect with VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/vrms
            cd apps/vrms

            echo "Stopping frontend container..."
            docker-compose stop frontend

            echo "Pulling latest frontend Docker image..."
            docker-compose pull frontend

            echo "Restarting the frontend service..."
            docker-compose up -d frontend

            echo "Cleaning up unused Docker images..."
            docker image prune -f

            echo "VRMS frontend deployment successful."