name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env file for React
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build and push frontend image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t nushan2000/vrs-frontend:latest .
          docker push nushan2000/vrs-frontend:latest

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 10.50.227.121
          username: vrsuser
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/vrs
            docker-compose pull frontend
            docker-compose up -d frontend
